// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package events

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID          string
	Name        string
	Description string
	Url         string
	AdminCode   string
	StartDate   pgtype.Timestamptz
	EndDate     pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}
