// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Proof Pass API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DefaultAPIService is a service that implements the logic for the DefaultAPIServicer
// This service should implement the business logic for every endpoint for the DefaultAPI API.
// Include any external packages or services that will be required by this service.
type DefaultAPIService struct {
}

// NewDefaultAPIService creates a default api service
func NewDefaultAPIService() *DefaultAPIService {
	return &DefaultAPIService{}
}

// EventsEventIdGet - Get event details
func (s *DefaultAPIService) EventsEventIdGet(ctx context.Context, eventId string) (ImplResponse, error) {
	// TODO - update EventsEventIdGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Event{}) or use other options such as http.Ok ...
	// return Response(200, Event{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("EventsEventIdGet method not implemented")
}

// EventsEventIdRequestTicketCredentialPost - Request a new ticket credential for an event
func (s *DefaultAPIService) EventsEventIdRequestTicketCredentialPost(ctx context.Context, eventId string) (ImplResponse, error) {
	// TODO - update EventsEventIdRequestTicketCredentialPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, UnencryptedTicketCredential{}) or use other options such as http.Ok ...
	// return Response(201, UnencryptedTicketCredential{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("EventsEventIdRequestTicketCredentialPost method not implemented")
}

// EventsGet - Get list of events
func (s *DefaultAPIService) EventsGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update EventsGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Event{}) or use other options such as http.Ok ...
	// return Response(200, []Event{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("EventsGet method not implemented")
}

// HealthGet - Check the health of the API
func (s *DefaultAPIService) HealthGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update HealthGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("HealthGet method not implemented")
}

// UserLoginPost - User login
func (s *DefaultAPIService) UserLoginPost(ctx context.Context, userLogin UserLogin) (ImplResponse, error) {
	// TODO - update UserLoginPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, LoginResponse{}) or use other options such as http.Ok ...
	// return Response(200, LoginResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UserLoginPost method not implemented")
}

// UserMeEmailCredentialGet - Get user email credential
func (s *DefaultAPIService) UserMeEmailCredentialGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update UserMeEmailCredentialGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, EmailCredential{}) or use other options such as http.Ok ...
	// return Response(200, EmailCredential{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UserMeEmailCredentialGet method not implemented")
}

// UserMeEmailCredentialPut - Store user email credential with encrypted data
func (s *DefaultAPIService) UserMeEmailCredentialPut(ctx context.Context, putEmailCredentialRequest PutEmailCredentialRequest) (ImplResponse, error) {
	// TODO - update UserMeEmailCredentialPut with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	// return Response(201, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UserMeEmailCredentialPut method not implemented")
}

// UserMeGet - Get user details
func (s *DefaultAPIService) UserMeGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update UserMeGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, User{}) or use other options such as http.Ok ...
	// return Response(200, User{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UserMeGet method not implemented")
}

// UserMeRequestEmailCredentialPost - Generate a new email credential
func (s *DefaultAPIService) UserMeRequestEmailCredentialPost(ctx context.Context) (ImplResponse, error) {
	// TODO - update UserMeRequestEmailCredentialPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, UnencryptedEmailCredential{}) or use other options such as http.Ok ...
	// return Response(201, UnencryptedEmailCredential{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UserMeRequestEmailCredentialPost method not implemented")
}

// UserMeTicketCredentialPut - Store user ticket credential with encrypted data
func (s *DefaultAPIService) UserMeTicketCredentialPut(ctx context.Context, putTicketCredentialRequest PutTicketCredentialRequest) (ImplResponse, error) {
	// TODO - update UserMeTicketCredentialPut with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	// return Response(201, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UserMeTicketCredentialPut method not implemented")
}

// UserMeTicketCredentialsGet - Get user ticket credentials
func (s *DefaultAPIService) UserMeTicketCredentialsGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update UserMeTicketCredentialsGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []TicketCredential{}) or use other options such as http.Ok ...
	// return Response(200, []TicketCredential{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UserMeTicketCredentialsGet method not implemented")
}

// UserRequestVerificationCodePost - Request an email verification code
func (s *DefaultAPIService) UserRequestVerificationCodePost(ctx context.Context, userEmailVerificationRequest UserEmailVerificationRequest) (ImplResponse, error) {
	// TODO - update UserRequestVerificationCodePost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UserRequestVerificationCodePost method not implemented")
}

// UserUpdatePut - Update user details
func (s *DefaultAPIService) UserUpdatePut(ctx context.Context, userUpdate UserUpdate) (ImplResponse, error) {
	// TODO - update UserUpdatePut with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, User{}) or use other options such as http.Ok ...
	// return Response(200, User{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UserUpdatePut method not implemented")
}
