/* tslint:disable */
/* eslint-disable */
/**
 * ZK Ticketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EmailCredential
 */
export interface EmailCredential {
    /**
     *
     * @type {string}
     * @memberof EmailCredential
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof EmailCredential
     */
    identityCommitment?: string;
    /**
     *
     * @type {string}
     * @memberof EmailCredential
     */
    data?: string;
    /**
     *
     * @type {Date}
     * @memberof EmailCredential
     */
    issuedAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof EmailCredential
     */
    expireAt?: Date;
}

/**
 * Check if a given object implements the EmailCredential interface.
 */
export function instanceOfEmailCredential(
    value: object,
): value is EmailCredential {
    return true;
}

export function EmailCredentialFromJSON(json: any): EmailCredential {
    return EmailCredentialFromJSONTyped(json, false);
}

export function EmailCredentialFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): EmailCredential {
    if (json == null) {
        return json;
    }
    return {
        id: json['id'] == null ? undefined : json['id'],
        identityCommitment:
            json['identity_commitment'] == null
                ? undefined
                : json['identity_commitment'],
        data: json['data'] == null ? undefined : json['data'],
        issuedAt:
            json['issued_at'] == null ? undefined : new Date(json['issued_at']),
        expireAt:
            json['expire_at'] == null ? undefined : new Date(json['expire_at']),
    };
}

export function EmailCredentialToJSON(value?: EmailCredential | null): any {
    if (value == null) {
        return value;
    }
    return {
        id: value['id'],
        identity_commitment: value['identityCommitment'],
        data: value['data'],
        issued_at:
            value['issuedAt'] == null
                ? undefined
                : value['issuedAt'].toISOString(),
        expire_at:
            value['expireAt'] == null
                ? undefined
                : value['expireAt'].toISOString(),
    };
}
