/* tslint:disable */
/* eslint-disable */
/**
 * ZK Ticketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Event
 */
export interface Event {
    /**
     *
     * @type {string}
     * @memberof Event
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof Event
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof Event
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof Event
     */
    url?: string;
    /**
     *
     * @type {string}
     * @memberof Event
     */
    adminCode?: string;
}

/**
 * Check if a given object implements the Event interface.
 */
export function instanceOfEvent(value: object): value is Event {
    return true;
}

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): Event {
    if (json == null) {
        return json;
    }
    return {
        id: json['id'] == null ? undefined : json['id'],
        name: json['name'] == null ? undefined : json['name'],
        description:
            json['description'] == null ? undefined : json['description'],
        url: json['url'] == null ? undefined : json['url'],
        adminCode: json['admin_code'] == null ? undefined : json['admin_code'],
    };
}

export function EventToJSON(value?: Event | null): any {
    if (value == null) {
        return value;
    }
    return {
        id: value['id'],
        name: value['name'],
        description: value['description'],
        url: value['url'],
        admin_code: value['adminCode'],
    };
}
