/* tslint:disable */
/* eslint-disable */
/**
 * ZK Ticketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UnencryptedEmailCredential
 */
export interface UnencryptedEmailCredential {
    /**
     *
     * @type {string}
     * @memberof UnencryptedEmailCredential
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof UnencryptedEmailCredential
     */
    credential?: string;
    /**
     *
     * @type {Date}
     * @memberof UnencryptedEmailCredential
     */
    issuedAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof UnencryptedEmailCredential
     */
    expireAt?: Date;
}

/**
 * Check if a given object implements the UnencryptedEmailCredential interface.
 */
export function instanceOfUnencryptedEmailCredential(
    value: object,
): value is UnencryptedEmailCredential {
    return true;
}

export function UnencryptedEmailCredentialFromJSON(
    json: any,
): UnencryptedEmailCredential {
    return UnencryptedEmailCredentialFromJSONTyped(json, false);
}

export function UnencryptedEmailCredentialFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): UnencryptedEmailCredential {
    if (json == null) {
        return json;
    }
    return {
        id: json['id'] == null ? undefined : json['id'],
        credential: json['credential'] == null ? undefined : json['credential'],
        issuedAt:
            json['issued_at'] == null ? undefined : new Date(json['issued_at']),
        expireAt:
            json['expire_at'] == null ? undefined : new Date(json['expire_at']),
    };
}

export function UnencryptedEmailCredentialToJSON(
    value?: UnencryptedEmailCredential | null,
): any {
    if (value == null) {
        return value;
    }
    return {
        id: value['id'],
        credential: value['credential'],
        issued_at:
            value['issuedAt'] == null
                ? undefined
                : value['issuedAt'].toISOString(),
        expire_at:
            value['expireAt'] == null
                ? undefined
                : value['expireAt'].toISOString(),
    };
}
