/* tslint:disable */
/* eslint-disable */
/**
 * ZK Ticketing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface User
 */
export interface User {
    /**
     *
     * @type {string}
     * @memberof User
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof User
     */
    email?: string;
    /**
     *
     * @type {string}
     * @memberof User
     */
    identityCommitment?: string;
    /**
     *
     * @type {string}
     * @memberof User
     */
    encryptedInternalNullifier?: string;
    /**
     *
     * @type {string}
     * @memberof User
     */
    encryptedIdentitySecret?: string;
    /**
     *
     * @type {Date}
     * @memberof User
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): User {
    if (json == null) {
        return json;
    }
    return {
        id: json['id'] == null ? undefined : json['id'],
        email: json['email'] == null ? undefined : json['email'],
        identityCommitment:
            json['identity_commitment'] == null
                ? undefined
                : json['identity_commitment'],
        encryptedInternalNullifier:
            json['encrypted_internal_nullifier'] == null
                ? undefined
                : json['encrypted_internal_nullifier'],
        encryptedIdentitySecret:
            json['encrypted_identity_secret'] == null
                ? undefined
                : json['encrypted_identity_secret'],
        createdAt:
            json['created_at'] == null
                ? undefined
                : new Date(json['created_at']),
    };
}

export function UserToJSON(value?: User | null): any {
    if (value == null) {
        return value;
    }
    return {
        id: value['id'],
        email: value['email'],
        identity_commitment: value['identityCommitment'],
        encrypted_internal_nullifier: value['encryptedInternalNullifier'],
        encrypted_identity_secret: value['encryptedIdentitySecret'],
        created_at:
            value['createdAt'] == null
                ? undefined
                : value['createdAt'].toISOString(),
    };
}
