// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package registrations

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Registration struct {
	ID      int32
	EventID pgtype.Text
	Email   string
}
