// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package registrations

import (
	"context"
)

const getEventRegistrations = `-- name: GetEventRegistrations :many
SELECT id, event_id, email
FROM registrations
WHERE event_id = $1
`

func (q *Queries) GetEventRegistrations(ctx context.Context, eventID string) ([]Registration, error) {
	rows, err := q.db.Query(ctx, getEventRegistrations, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Registration
	for rows.Next() {
		var i Registration
		if err := rows.Scan(&i.ID, &i.EventID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOneByEventIdAndEmail = `-- name: GetOneByEventIdAndEmail :one
SELECT id, event_id, email
FROM registrations
WHERE event_id = $1
    AND email = $2
`

type GetOneByEventIdAndEmailParams struct {
	EventID string
	Email   string
}

func (q *Queries) GetOneByEventIdAndEmail(ctx context.Context, arg GetOneByEventIdAndEmailParams) (Registration, error) {
	row := q.db.QueryRow(ctx, getOneByEventIdAndEmail, arg.EventID, arg.Email)
	var i Registration
	err := row.Scan(&i.ID, &i.EventID, &i.Email)
	return i, err
}

const getRegisteredEventsByEmail = `-- name: GetRegisteredEventsByEmail :many
SELECT id, event_id, email
FROM registrations
WHERE email = $1
`

func (q *Queries) GetRegisteredEventsByEmail(ctx context.Context, email string) ([]Registration, error) {
	rows, err := q.db.Query(ctx, getRegisteredEventsByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Registration
	for rows.Next() {
		var i Registration
		if err := rows.Scan(&i.ID, &i.EventID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
