// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package ticket_credentials

import (
	"context"
)

const getAllByEmail = `-- name: GetAllByEmail :many
SELECT id, email, event_id, data, issued_at, expire_at
FROM ticket_credentials
WHERE email = $1
ORDER BY issued_at DESC
`

func (q *Queries) GetAllByEmail(ctx context.Context, email string) ([]TicketCredential, error) {
	rows, err := q.db.Query(ctx, getAllByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketCredential
	for rows.Next() {
		var i TicketCredential
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EventID,
			&i.Data,
			&i.IssuedAt,
			&i.ExpireAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
