// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package users

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                         string
	Email                      string
	IdentityCommitment         string
	EncryptedInternalNullifier string
	EncryptedIdentitySecret    string
	CreatedAt                  pgtype.Timestamptz
}
