// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package users

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                         int32
	Email                      string
	IdentityCommitment         pgtype.Text
	EncryptedInternalNullifier pgtype.Text
	EncryptedIdentitySecret    pgtype.Text
	CreatedAt                  pgtype.Timestamp
}
