// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package users

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
        id,
        email,
        identity_commitment,
        encrypted_internal_nullifier,
        encrypted_identity_secret,
        created_at
    )
VALUES ($1, $2, '', '', '', NOW())
RETURNING id, email, identity_commitment, encrypted_internal_nullifier, encrypted_identity_secret, created_at
`

type CreateUserParams struct {
	ID    string
	Email string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IdentityCommitment,
		&i.EncryptedInternalNullifier,
		&i.EncryptedIdentitySecret,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, identity_commitment, encrypted_internal_nullifier, encrypted_identity_secret, created_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IdentityCommitment,
		&i.EncryptedInternalNullifier,
		&i.EncryptedIdentitySecret,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, identity_commitment, encrypted_internal_nullifier, encrypted_identity_secret, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IdentityCommitment,
		&i.EncryptedInternalNullifier,
		&i.EncryptedIdentitySecret,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET identity_commitment = $1,
    encrypted_internal_nullifier = $2,
    encrypted_identity_secret = $3
WHERE id = $4
RETURNING id, email, identity_commitment, encrypted_internal_nullifier, encrypted_identity_secret, created_at
`

type UpdateUserParams struct {
	IdentityCommitment         string
	EncryptedInternalNullifier string
	EncryptedIdentitySecret    string
	ID                         string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.IdentityCommitment,
		arg.EncryptedInternalNullifier,
		arg.EncryptedIdentitySecret,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IdentityCommitment,
		&i.EncryptedInternalNullifier,
		&i.EncryptedIdentitySecret,
		&i.CreatedAt,
	)
	return i, err
}
